[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundr

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
